server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rms?currentSchema=rms
    username: postgres
    password: rms!#24

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-fetch-size: 100
    default-statement-timeout: 30
  type-aliases-package: com.smart.rms.system.model, com.smart.rms.architecture.model, com.smart.rms.common.map
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    root: info
    com.smart.rms: debug
    org.mybatis: debug
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
