server:
  port: 8080

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/rms?currentSchema=rms
    username: postgres
    password: rms!#24

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-fetch-size: 100
    default-statement-timeout: 30
  type-aliases-package: com.smart.rms.system.model, com.smart.rms.architecture.model, com.smart.rms.common.map
  mapper-locations: classpath:mapper/**/*.xml


logging:
  level:
    com.smart.rms: debug
    org.mybatis: debug
    org.apache.ibatis: debug
